### Create new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email":"mail2@example.com",
  "password":"password"
}

### Login user

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email":"mail1@example.com",
  "password":"password"
}

### sign out user

POST http://localhost:3000/auth/signout
Content-Type: application/json

{}

### Get current user
GET http://localhost:3000/auth/me

### Get all users
GET http://localhost:3000/auth/

### Get user by id
GET http://localhost:3000/auth/2

### Delete user by id
DELETE http://localhost:3000/auth/1

### Patch user by id
PATCH  http://localhost:3000/auth/2
Content-Type: application/json

{
  "password":"pass"
}
